# Model arguments
model_name_or_path: /data/vayu/train/models/DeepSeek-R1-Distill-Qwen-32B
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
dataset_name: AI-MO/NuminaMath-TIR
dataset_configs:
- all

# GRPO trainer config
bf16: true
use_vllm: true
vllm_device: cuda:4
vllm_tensor_parallel_size: 4
vllm_gpu_memory_utilization: 0.9
do_eval: true
eval_strategy: steps
eval_steps: 100
gradient_accumulation_steps: 8
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: DeepSeek-R1-Distill-Qwen-32B-GRPO
hub_strategy: every_save
learning_rate: 5.0e-06
log_level: info
logging_steps: 5
logging_strategy: steps
lr_scheduler_type: cosine
max_prompt_length: 512
max_completion_length: 1024
max_steps: -1
num_generations: 2
num_train_epochs: 1
output_dir: data/DeepSeek-R1-Distill-Qwen-32B-GRPO
overwrite_output_dir: true
per_device_eval_batch_size: 1
per_device_train_batch_size: 1
push_to_hub: true
report_to:
- wandb
save_strategy: "no"
seed: 42
warmup_ratio: 0.1
