# 全面场景分类配置表 v2.0

base_dimensions:
  # 30大行业分类
  industries:
    # 科技创新产业
    - 人工智能与机器学习
    - 半导体与集成电路
    - 量子计算与通信
    - 生物科技与基因工程
    - 新能源与清洁技术
    
    # 信息技术产业
    - 云计算与数据中心
    - 网络安全与隐私保护
    - 物联网与智能设备
    - 区块链与分布式技术
    - 软件开发与服务
    
    # 制造业
    - 智能制造与工业4.0
    - 航空航天工程
    - 新材料研发与应用
    - 汽车与智能交通
    - 机器人与自动化
    
    # 生命科学
    - 医疗器械与设备
    - 生物医药研发
    - 健康管理与养老
    - 脑科学与神经工程
    - 基因治疗与精准医疗
    
    # 现代服务业
    - 金融科技与服务
    - 教育培训与发展
    - 文化创意与娱乐
    - 电子商务与零售
    - 物流与供应链
    
    # 可持续发展
    - 环境保护与治理
    - 智慧城市建设
    - 可再生能源利用
    - 农业科技与食品
    - 海洋资源开发
    
    # 前沿科技
    - 元宇宙与虚拟现实
    - 合成生物学
    - Web3.0与去中心化
    - 脑机接口技术
    - 高级计算架构

  # 60个应用场景
  scenarios:
    # 日常生活（15个）
    daily_life:
      - 智能家居控制
      - 个人健康监测
      - 在线教育学习
      - 社交媒体互动
      - 移动支付交易
      - 智能出行导航
      - 娱乐内容推荐
      - 家庭安防监控
      - 智能家电管理
      - 个人助理服务
      - 远程办公协作
      - 生活服务预订
      - 健康饮食指导
      - 运动健身规划
      - 家庭能源管理

    # 专业领域（25个）
    professional:
      - 医疗诊断辅助
      - 手术规划模拟
      - 药物研发分析
      - 金融风险评估
      - 投资组合管理
      - 法律文书生成
      - 专利分析检索
      - 教学课程规划
      - 学生能力评估
      - 工业设备维护
      - 产品质量控制
      - 供应链优化
      - 市场趋势分析
      - 客户行为预测
      - 广告精准投放
      - 城市交通调度
      - 环境污染监测
      - 气象预报分析
      - 农作物监测
      - 地质勘探分析
      - 建筑设计规划
      - 网络安全防护
      - 数据隐私保护
      - 能源调度优化
      - 资源分配规划

    # 特殊场景（20个）
    special:
      - 太空探测任务
      - 深海资源勘探
      - 核电站监控
      - 高原科考作业
      - 极地环境作业
      - 灾害应急响应
      - 文化遗产保护
      - 国防军事演练
      - 深度伪造检测
      - 舆情分析监测
      - 碳排放监测
      - 生物多样性保护
      - 极端天气应对
      - 传染病防控
      - 食品安全溯源
      - 数字孪生模拟
      - 智慧养老服务
      - 智能交通管控
      - 城市安全预警
      - 公共卫生监测

  # 50个核心功能
  capabilities:
    # 认知能力（15个）
    cognitive:
      - 逻辑推理分析
      - 知识图谱构建
      - 因果关系推断
      - 模式规律识别
      - 概念抽象归纳
      - 决策优化评估
      - 知识迁移应用
      - 多任务协同学习
      - 时空关系理解
      - 语义理解分析
      - 上下文推理
      - 异常检测识别
      - 知识更新进化
      - 记忆存储检索
      - 认知偏差纠正

    # 感知交互（20个）
    perceptual:
      - 计算机视觉处理
      - 自然语言理解
      - 语音识别转换
      - 多模态信息融合
      - 手势动作识别
      - 表情情绪识别
      - 生物特征识别
      - 场景三维重建
      - 实时目标跟踪
      - 图像语义分割
      - 声纹识别分析
      - 触觉感知反馈
      - 空间定位导航
      - 增强现实交互
      - 虚拟现实沉浸
      - 脑机接口控制
      - 多语言实时翻译
      - 人机对话交互
      - 体感动作捕捉
      - 环境感知适应

    # 创新能力（15个）
    creative:
      - 科学假设生成
      - 创意设计构思
      - 艺术作品创作
      - 音乐旋律作曲
      - 文学创作写作
      - 产品创新设计
      - 解决方案优化
      - 商业模式创新
      - 技术路径规划
      - 实验方案设计
      - 教学课程创新
      - 游戏关卡设计
      - 营销策略创新
      - 服务流程优化
      - 交互体验设计


# 版本信息
version_info:
  version: 2.0.0
  last_updated: "2025-02-01"

